//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMaster.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LandingPageText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LandingPageText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskMaster.Web.Resources.LandingPageText", typeof(LandingPageText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam id tristique odio. Duis vitae odio nisi. Proin bibendum convallis gravida. Suspendisse non nulla convallis, tincidunt velit aliquet, semper elit..
        /// </summary>
        public static string HowItWorks1 {
            get {
                return ResourceManager.GetString("HowItWorks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusce nec enim eu magna varius vulputate. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas..
        /// </summary>
        public static string HowItWorks2 {
            get {
                return ResourceManager.GetString("HowItWorks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sed venenatis, quam vel hendrerit maximus, dui urna tempor leo, ullamcorper hendrerit diam magna ac ipsum..
        /// </summary>
        public static string HowItWorks3 {
            get {
                return ResourceManager.GetString("HowItWorks3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak działa aplikacja?.
        /// </summary>
        public static string HowItWorksTitle {
            get {
                return ResourceManager.GetString("HowItWorksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzięki aplikacji TaskMaster możesz mierzyć czas wykonywania twoich zadań. To proste, wystarczy pobrać aplikację mobilną, dodać task i zająć się daną aktywnością - resztę zrobi za ciebie TaskMaster..
        /// </summary>
        public static string leftAdditionalText {
            get {
                return ResourceManager.GetString("leftAdditionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapanuj nad swoim czasem!.
        /// </summary>
        public static string leftMainText {
            get {
                return ResourceManager.GetString("leftMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string signIn {
            get {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string signInButton {
            get {
                return ResourceManager.GetString("signInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        public static string signUp {
            get {
                return ResourceManager.GetString("signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj.
        /// </summary>
        public static string signUpButton {
            get {
                return ResourceManager.GetString("signUpButton", resourceCulture);
            }
        }
    }
}
